### ISSUE TITLE
This code is too long for no reason.

### ISSUE THREAD

**Issue by ghost** [owersite/sigma-wiper#2]
# Bad code!
For a program that could be written in ~60-70 lines max, you decided to extend it to 400 lines for some reason + half of that being empty spaces...

Also the platform check is really useless as there's no point in checking due to your code not working anyways on Linux/OS X due to the difference in paths + the framework you're using not being supported on any other platforms *except* Windows.

**Comment by owersite** [comment]
Howdy, fgets! Well yes, the framework isnt meant to work on any other platforms than windows but there are tools which can help run such files from OS X/Linux, for the code i find it clean enough and don't think it's too long! This repo is nothing more than the repo from group i was enspired by, but some sort of contribution to them as they are strongly selfless and good, big love!
