### ISSUE TITLE
add linux support

### ISSUE THREAD

**Issue by ghost** [owersite/sigma-wiper#3]

**Comment by owersite** [comment]
Hello! I do not use any Linux OS, but i may add it if i have someone to test it for me and give me linux directories comparing to windows that i can use, just like i did in my variables that you can find on lines 140 - 148.

**Comment by ghost** [comment]
Since there is no linux support, i've made a fork of your project written in python with linux support.
You can check it out https://github.com/RandomVersion/sigma-wiper-py
EDIT: i accidentally changed the license to GPL 3 instead of your license
